### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for WSDDN:

### ISSUE THREAD

**Issue by Unrealluver** [adursun/wsddn.pytorch#17]
Hey bro, when I tried to run the command:
python3.7 src/evaluate.py --state_path="./states/epoch_20_with_scores.pt" 

I got this:
Traceback (most recent call last):
  File "src/evaluate.py", line 22, in <module>
    net.load_state_dict(torch.load(args.state_path))
  File "/usr/local/python3/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/python3/lib/python3.7/site-packages/torch/serialization.py", line 574, in _load
    result = unpickler.load()
  File "/usr/local/python3/lib/python3.7/site-packages/torch/serialization.py", line 537, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/usr/local/python3/lib/python3.7/site-packages/torch/serialization.py", line 119, in default_restore_location
    result = fn(storage, location)
  File "/usr/local/python3/lib/python3.7/site-packages/torch/serialization.py", line 99, in _cuda_deserialize
    return storage_type(obj.size())
  File "/usr/local/python3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 599, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
KeyboardInterrupt

Would you like to tell me how to use the saved model args to do evaluate?

**Comment by adursun** [comment]
Hi,

I added weights for pretrained AlexNet based model. If you already cloned the code, you can run the following commands to evaluate AlexNet based model.

```bash
wget https://www.dropbox.com/s/lifv1ywa98a2p4y/alexnet_epoch_20.pt -P states/
python src/evaluate.py --base_net alexnet --state_path states/alexnet_epoch_20.pt
```

Thank you for your interest.
